in:
  type: union
  columns:
    - { name: id, type: long }
    - { name: description, type: string }
    - { name: name, type: string }
    - { name: t, type: timestamp, format: "%Y-%m-%d %H:%M:%S %z"}
    - { name: payload, type: json}
    - { name: group_name, type: string}
  union:
    - in:
        type: file
        path_prefix: ./example/data01
        parser:
          type: csv
          delimiter: "\t"
          skip_header_lines: 0
          null_string: ""
          columns:
            - { name: id, type: long }
            - { name: description, type: string }
            - { name: name, type: string }
            - { name: t, type: timestamp, format: "%Y-%m-%d %H:%M:%S %z"}
            - { name: payload, type: json}
          stop_on_invalid_record: true
      filters:
        - type: column
          add_columns:
            - {name: group_name, type: string, default: "data01"}
    - in:
        type: file
        path_prefix: ./example/data02
        parser:
          type: csv
          delimiter: "\t"
          skip_header_lines: 0
          null_string: ""
          columns:
            - { name: id, type: long }
            - { name: description, type: string }
            - { name: name, type: string }
            - { name: t, type: timestamp, format: "%Y-%m-%d %H:%M:%S %z"}
            - { name: payload, type: json}
          stop_on_invalid_record: true
      filters:
        - type: column
          add_columns:
            - {name: group_name, type: string, default: "data02"}

out:
  type: stdout

